-- NorthQuest: Supabase schema + seed data
-- Run in Supabase SQL editor.

create table if not exists public.destinations (
  id bigint generated by default as identity primary key,
  name text not null,
  state text not null,
  description text not null,
  image text not null,
  eco_score int not null check (eco_score >= 0 and eco_score <= 100),
  culture_highlight text not null,
  is_hidden_gem boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_query text not null,
  itinerary_json jsonb not null,
  created_at timestamptz not null default now()
);

-- Enable RLS (recommended). Policies below allow public read of destinations.
alter table public.destinations enable row level security;
alter table public.trips enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'destinations' and policyname = 'Public read destinations'
  ) then
    create policy "Public read destinations"
    on public.destinations
    for select
    using (true);
  end if;
end$$;

-- Trips: allow inserts only via service role (no public policy).

-- Seed: popular destinations
insert into public.destinations (name, state, description, image, eco_score, culture_highlight, is_hidden_gem)
values
  ('Jaipur', 'Rajasthan', 'Pink City of forts, bazaars, and royal palaces.', 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=70', 52, 'Amber Fort, City Palace, and block-printed textiles.', false),
  ('Agra', 'Uttar Pradesh', 'Mughal-era architecture and timeless monuments.', 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=70', 40, 'Taj Mahal at sunrise; Agra Fort storytelling walks.', false),
  ('Rishikesh', 'Uttarakhand', 'Ganga ghats, yoga ashrams, and rafting adventures.', 'https://images.unsplash.com/photo-1597040663342-45b6af3d91a5?auto=format&fit=crop&w=1200&q=70', 74, 'Ganga Aarti + yoga traditions in the Himalayas foothills.', false),
  ('Leh', 'Ladakh', 'High-altitude desert landscapes and monastery trails.', 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=70', 78, 'Thiksey/Hemis monasteries; Ladakhi food and crafts.', false),
  ('Varanasi', 'Uttar Pradesh', 'Spiritual riverfront city with ancient lanes and rituals.', 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1200&q=70', 35, 'Kashi Vishwanath, ghats, and classical music heritage.', false),
  ('Spiti Valley', 'Himachal Pradesh', 'Remote cold desert with stark mountains and villages.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=70', 86, 'Key Monastery; homestays and high-altitude culture.', false)
on conflict do nothing;

-- Seed: hidden gems
insert into public.destinations (name, state, description, image, eco_score, culture_highlight, is_hidden_gem)
values
  ('Tirthan Valley', 'Himachal Pradesh', 'Riverside hamlets and Great Himalayan National Park gateways.', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=70', 90, 'Local trout cuisine and forest trail culture.', true),
  ('Kalpa', 'Himachal Pradesh', 'Apple orchards and Kinnaur Kailash views.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=70', 88, 'Kinnauri architecture, shawls, and temple legends.', true),
  ('Chitkul', 'Himachal Pradesh', 'Last village near Indo-Tibet border with alpine scenery.', 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=70', 87, 'Baspa Valley traditions and wooden homes.', true),
  ('Chopta', 'Uttarakhand', 'Mini-Switzerland meadow base for Tungnath trek.', 'https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1200&q=70', 91, 'Kedarnath region folklore and Himalayan temple trails.', true),
  ('Munsiyari', 'Uttarakhand', 'Panchachuli views, village walks, and slow travel.', 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=70', 89, 'Kumaoni food + trans-Himalayan trade route stories.', true)
on conflict do nothing;

